### ISSUE TITLE
`num_knots` pass through option

### ISSUE THREAD

**Issue by benkeser** [nhejazi/haldensify#34]
Is it possible to add an option to specify the number of knots that gets passed through to `fit_hal`? It seems the current implementation is relying on the default, which [may not be appropriate for all use cases](https://github.com/tlverse/hal9001/issues/98).

**Comment by Larsvanderlaan** [comment]
This should already be possible, e.g. fit_hal(X,Y, max_degree  = 3, num_knots = c(100, 50, 10), smoothness_orders = 1).

 If max_degree = 3 and num_knots = c(100, 50, 10) then all one-way basis functions will be generated based on a equal quantile-spaced grid of 100 knot points for all covariates, all two-way basis functions based on a equal quantile-spaced grid of 50 knot points for all covariates, all three-way basis functions  based on a equal quantile-spaced grid of 10 knot points for all covariates.

The "num_knots_generator" function was not necessarily intended to be used by the user and was just used to set the default values in a way that depends on the previously passed arguments. Maybe to avoid confusion, it would be better to have "num_knots = NULL" by default and then convert this to the previous default setting inside the fit_hal function.

**Comment by nhejazi** [comment]
sure, that shouldn't be a problem. before trying that though, am i correct in understanding that the `...` (https://github.com/nhejazi/haldensify/blob/master/R/haldensify.R#L216-L217) does not work for this currently?

**Comment by benkeser** [comment]
No actually I think that will work. @Scarlett422301, can you try to pass through `num_knots`?

**Comment by Scarlett422301** [comment]
sure!

**Comment by nhejazi** [comment]
great, closing for now, but feel free to re-open if this does need to be addressed
