### ISSUE TITLE
checking haldensify takes over 7 hours

### ISSUE THREAD

**Issue by tdhock** [nhejazi/haldensify#39]
Hi @nhejazi 
I am trying to check haldensify, to determine if there are any revdep issues with data.table https://github.com/tdhock/data.table-revdeps/issues/17#issuecomment-1951449062

I have observed that checking haldensify takes over 7 hours, with most of the time being spent in the "re-building of vignette outputs" step. 
In your experience, is it normal for checking haldensify to take so long? If not, is there any special setup that you would recommend to speed up checks?
Would you please consider removing, or modifying the code, in some of the vignettes, in order to make re-building faster? (at least in the version you submit to CRAN)

For context, we are checking every revdep of data.table every day, and there are 1400+ such packages. Median check time is about 10 minutes over all of those packages. haldensify is in the top 2 slowest. It runs out of time after a limit of 9 hours. 99% of packages take 2 hours or less total check time. 

Thanks in advance for any help or clarification you can provide.

**Comment by nhejazi** [comment]
thanks for reporting this @tdhock, and sorry to hear that `haldensify` is causing some issues with the revdep checks on `data.table`. while i'm happy to help modify `haldensify` as needed to resolve this, the checking time that you're running into seems quite inflated relative to what i've encountered in the past.

to make sure, i double checked the build time for this step by re-activating github actions on this repo (it had been a while and they'd stopped working / the logs had been cleared), which reports <1min for the step "re-building of vignette outputs" (see https://github.com/nhejazi/haldensify/actions/runs/7969303140/job/21754908011#step:8:113), and i also took a look at the CRAN build logs (https://www.r-project.org/nosvn/R.check/r-devel-linux-x86_64-debian-clang/haldensify-00check.html), which report a longer time of <400sec ~= 7min. fwiw, i'm pretty sure CRAN has a policy related to such excessive build/check times and would have removed the package from their repository if the issue persisted.

**Comment by tdhock** [comment]
Hi Nima, thanks for the quick feedback. 
The comparisons with github actions and CRAN machines are interesting.
I ran check with --timings and I got the following output which shows timings for examples
```
* checking examples ... OK
Examples with CPU (user + system) or elapsed time > 5s
                          user system elapsed
predict.haldensify     232.844  0.223 233.847
haldensify             224.986  0.094 225.795
fit_haldensify         191.567  0.091 192.164
print.haldensify        62.224  0.119  62.587
confint.ipw_haldensify  27.379  0.153  27.624
ipw_shift               26.807  0.059  26.964
print.ipw_haldensify    26.790  0.050  26.946
plot.haldensify          6.767  0.021   6.819
* checking for unstated dependencies in 'tests' ... OK
* checking tests ...
  Running 'testthat.R'
 OK
```
these seem very large too.
I don't really understand why it would be so slow on my computer, yet so reasonable on yours/actions/CRAN.
I wonder if your code does something on the file system? (my computer uses a network file system so it may be partially my issue?)

**Comment by nhejazi** [comment]
closing as stale since couldn't be replicated
